# Generated by Django 3.0 on 2019-12-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='number_of_songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='author',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
